### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

### ISSUE THREAD

**Issue by jasesmith** [Nicolab/atom-local-history#19]
[Enter steps to reproduce below:]

1. Clicked 'Packages › Local History › Show current file' in Atom menu bar.
2. Error is thrown. 

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [local-history](https://github.com/Nicolab/atom-local-history) package, v2.3.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5830

Error: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
  at Error (native)
  at Function.jQuery.extend.buildFragment (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5830:27)
  at WorkspaceView.jQuery.fn.extend.domManip (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5636:22)
  at WorkspaceView.jQuery.fn.extend.append (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5458:15)
  at WorkspaceView.jQuery.fn.(anonymous function) [as append] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:396:31)
  at LocalHistoryView.findLocalHistory (/Users/Jase/.atom/packages/local-history/lib/local-history-view.js:127:22)
  at atom-workspace.<anonymous> (/Users/Jase/.atom/packages/local-history/lib/local-history.js:50:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:157:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:73:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
  2x -3:19.1 core:move-right (atom-text-editor.editor)
     -3:18.5 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -3:18.2 editor:select-to-first-character-of-line (atom-text-editor.editor)
     -3:17.1 core:copy (atom-text-editor.editor)
     -3:13.6 editor:newline (atom-text-editor.editor)
     -3:13.1 core:paste (atom-text-editor.editor)
     -3:12.2 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -3:11.3 core:move-right (atom-text-editor.editor)
     -3:10.9 editor:select-to-end-of-word (atom-text-editor.editor)
  4x -3:10.5 core:select-left (atom-text-editor.editor)
     -3:08.6 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -3:04.6 core:move-right (atom-text-editor.editor)
     -3:04.1 core:select-down (atom-text-editor.editor)
     -3:03.4 core:backspace (atom-text-editor.editor)
     -3:02.5 core:save (atom-text-editor.editor)
     -0:01.7 local-history:current-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".sass-cache",
      ".tmp"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "autocomplete-paths",
      "project-colorize",
      "atom-terminal",
      "color-picker",
      "notebook",
      "Zen",
      "welcome",
      "timecop",
      "linter-less",
      "linter-scss-lint",
      "linter-csslint",
      "deprecation-cop"
    ],
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ]
  },
  "local-history": {}
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
editor-stats, v0.17.0
file-icons, v1.5.2
git-tab-status, v1.6.0
highlight-line, v0.10.1
hipster-ipsum, v0.1.0
jsonpp, v0.0.6
linter, v0.12.0
linter-jshint, v0.1.0
local-history, v2.3.0
minimap, v4.7.1
newton-dark-syntax, v1.1.1
newton-dark-ui, v1.0.4
pretty-json, v0.3.2
project-palette-finder, v2.4.16
symbols-tree-view, v0.8.3
tree-view-breadcrumb, v0.4.1

# Dev
No dev packages
```

**Comment by jasesmith** [comment]
Not sure why it barfed like that. Seems to be working now. Closing this.

**Comment by Nicolab** [comment]
It's a great report!

If this problem is happening again, in the line [local-history-view.js:127](https://github.com/Nicolab/atom-local-history/blob/master/lib/local-history-view.js#L127) the code is `atom.workspaceView.append(this);` handled by the module `space-pen`.

It seems to have tried to delete a node that is no longer present (maybe a closed or moved element).

**Comment by blaize9** [comment]
The last time I had an issue it was with my Difftool Command setting I had an extra unexpected character (").
Error: C:\Program Files (x86)\Beyond Compare 4\BCompare.exe__"__ "{current-file}" "{revision-file}"
No Error: C:\Program Files (x86)\Beyond Compare 4\BCompare.exe "{current-file}" "{revision-file}"
