### ISSUE TITLE
[Windows] Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by zhopan77** [Nicolab/atom-local-history#60]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [local-history](https://github.com/Nicolab/atom-local-history) package 4.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\zpan\.atom\packages\local-history\node_modules\atom-message-panel\lib\MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/local-history/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/indent-detective/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (~/Atom/resources/app/static/<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (~/Atom/resources/app/static/<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (~/Atom/resources/app/static/<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (~/Atom/resources/app/static/<embedded>:11:284598)
```

### Commands

```
     -9:33.7.0 script:run (input.hidden-input)
     -8:45 core:move-right (input.hidden-input)
     -8:44.7.0 editor:select-to-end-of-line (input.hidden-input)
     -8:44.4.0 core:select-left (input.hidden-input)
     -8:44.1.0 intentions:highlight (input.hidden-input)
     -8:44 core:copy (input.hidden-input)
     -8:22.1.0 script:run (input.hidden-input)
 26x -6:23 intentions:highlight (input.hidden-input)
     -5:16.3.0 script:run (input.hidden-input)
     -2:29.2.0 julia-client:run-all (input.hidden-input)
     -2:26.5.0 script:run (input.hidden-input)
     -0:30.7.0 intentions:highlight (input.hidden-input)
     -0:30.4.0 command-palette:toggle (input.hidden-input)
     -0:15.5.0 script:run-options (input.hidden-input)
     -0:08.9.0 editor:consolidate-selections (input.hidden-input)
     -0:08.9.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-debugger 0.1.6 
atom-ide-datatip 0.11.1 
atom-ide-markdown-service 1.2.3 
atom-terminal-powershell 1.1.0 
bracket-colorizer 1.4.0 
build-cargo 2.0.0 
busy-signal 2.0.1 
file-icons 2.1.36 
ftp-remote-edit 0.18.0 
highlight-line 0.12.0 
highlight-selected 0.16.0 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.11.7 
intentions 1.1.5 
julia-client 0.11.3 
jumpy 5.0.2 
juno-toolbar-plus 0.6.0 
language-julia 0.19.2 
last-cursor-position 0.9.3 
latex-completions 0.3.6 
local-history 4.3.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-quick-highlight 1.0.1 
minimap-selection 4.5.0 
project-plus 1.0.0 
python-debugger 0.2.0 
quick-highlight 0.13.0 
script 3.25.0 
sync-settings 0.8.6 
TabNine 2.1.7 
tool-bar 1.2.0 
uber-juno 0.3.0 
```

**Comment by Nicolab** [comment]
I do not have a Windows to reproduce...

PR is welcome

**Comment by CleverOscar** [comment]
Has this error been resolved? I am not able to exit when I 'run script' inside my code editor. 

I keep getting the same issue only when I want to end an execution

**Comment by Nicolab** [comment]
No, PR is welcome

**Comment by CleverOscar** [comment]
I typed this into the terminal `brew reinstall python@2` then entered `pip install python-language-server` that solved my issues. Hopefully, that helps. I ended up just re-installing python@3 after the issues were solved.

**Comment by woolgathering** [comment]
Also having this error on Linux. I'll try and trace it when I have some more time.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: [local-history](https://github.com/Nicolab/atom-local-history) package 4.3.1


### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /home/jacob/.atom/packages/local-history/node_modules/atom-message-panel/lib/MessagePanelView.js:189

TypeError: Cannot read property 'remove' of undefined
    at ScriptView.MessagePanelView.remove (/packages/local-history/node_modules/atom-message-panel/lib/MessagePanelView.js:189:30)
    at ScriptView.detach (/packages/atom-python-virtualenv/node_modules/jquery/dist/jquery.js:5357:15)
    at ScriptView.removePanel (/packages/script/lib/script-view.js:89:10)
    at Object.closeScriptViewAndStopRunner (/packages/script/lib/script.js:161:21)
    at HTMLElement.coreCancel (/packages/script/lib/script.js:92:33)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1254747)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1250881)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -4:17.8.0 command-palette:toggle (input.hidden-input)
  2x -4:16 core:backspace (input.hidden-input)
     -4:14.8.0 core:move-down (input.hidden-input)
     -4:14.3.0 core:confirm (input.hidden-input)
     -4:14.3.0 virtualenv:select (input.hidden-input)
     -4:14.1.0 core:confirm (input.hidden-input)
     -4:13.3.0 script:run (input.hidden-input)
     -4:12.5.0 editor:consolidate-selections (input.hidden-input)
     -4:12.5.0 core:cancel (input.hidden-input)
     -2:03.9.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-woolgathering-dark-syntax.theme-atom-material-ui)
     -0:02.7.0 editor:consolidate-selections (input.hidden-input)
     -0:02.7.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-bracket-highlight 0.3.2 
atom-ctags 5.1.2 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
atom-latex 0.9.1 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-python-virtualenv 1.0.4 
atom-updater-linux 1.3.0 
autocomplete-python 1.16.0 
browser-plus 0.0.98 
build 0.70.0 
build-cmake 0.12.0 
busy-signal 2.0.1 
expand-region 0.5.0 
find-scroll-marker 0.1.3 
font-viewer 0.3.1 
git-plus 8.7.1 
highlight-selected 0.17.0 
Hydrogen 2.14.1 
hydrogen-python 0.0.8 
intentions 1.1.5 
kite 0.178.0 
language-cmake 1.2.0 
language-latex 1.2.0 
language-matlab 0.2.1 
local-history 4.3.1 
markdown-pdf 2.3.3 
markdown-preview-plus 3.11.5 
multi-cursor 3.0.0 
pdf-view 0.72.0 
platformio-ide-terminal 2.10.0 
processing 0.13.0 
processing-language 0.2.0 
reindent 1.5.0 
schelp-syntax 0.6.3 
script 3.25.0 
scroll-marker 0.3.2 
sequential-number 0.5.0 
split-diff 1.6.1 
supercollider 0.9.1 
tabs-to-spaces 1.0.5 
woolgathering-dark-syntax 1.10.0 
woolgathering-light-syntax 1.10.0 
```

**Comment by Nicolab** [comment]
@CleverOscar's solution seem to work.
